rentoCarEliteSystem/rentoCarEliteSystem/Models/ErrorViewModel.cs
namespace rentoCarEliteSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

rentoCarEliteSystem/rentoCarEliteSystem/Controllers/BookingController.cs
using BussinesLayer;
using Microsoft.AspNetCore.Mvc;

namespace rentoCarEliteSystem.Controllers
{
    public class BookingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public EntityLayer.systemEntities.ResponseEL createBooking([FromBody] EntityLayer.BookingEL bookingToCreate)
        {
            BoookingBL myBooking = new BoookingBL();
            return myBooking.createBooking(bookingToCreate);
        }


        [HttpGet]
        public List<EntityLayer.BookingEL> getBookingsByCustomerId(int customerId)
        {
            BoookingBL myBooking = new BoookingBL();
            return myBooking.getBookingsByCustomerId(customerId);
        }

        public List<EntityLayer.BookingEL> getBookingsByVechileId(int vehicleId)
        {
            BoookingBL myBooking = new BoookingBL();
            return myBooking.getBookingsByVechileId(vehicleId);
        }


        public List<EntityLayer.systemEntities.DashBoardEL> getDashBoardData()
        {
            BoookingBL myBooking = new BoookingBL();
            return myBooking.getDashBoardData();
        }

        [HttpDelete]
        public EntityLayer.systemEntities.ResponseEL deleteBooking(int bookingId)
        {
            BoookingBL myBooking = new BoookingBL();
            return myBooking.deleteBooking(bookingId);
        }
    }
}

rentoCarEliteSystem/rentoCarEliteSystem/Controllers/CustomerController.cs
using BussinesLayer;
using EntityLayer;
using EntityLayer.systemEntities;
using Microsoft.AspNetCore.Mvc;

namespace rentoCarEliteSystem.Controllers
{
    public class CustomerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ModalCreateCustomer()
        {
            return PartialView("ModalCreateCustomer");
        }


        [HttpPost]
        public  ResponseEL createCustomer([FromBody] CustomerEL customerToCreate)
        {
            CustomerBL myCustomer = new CustomerBL();
            return myCustomer.createCustomer(customerToCreate);
            
        }

        [HttpGet]
        public List<CustomerEL> getAllCustomer()
        {
            CustomerBL myCustomer = new CustomerBL();
            return myCustomer.getAllCustomer();
        }

        [HttpDelete]
        public  ResponseEL deleteCustomer(int id)
        {
            CustomerBL myCustomer = new CustomerBL();
            return myCustomer.deleteCustomer(id);
        }


        [HttpPut]
        public  ResponseEL updateCustomer([FromBody] CustomerEL customerToUpdate)
        {
            CustomerBL myCustomer = new CustomerBL();
            return myCustomer.updateCustomer(customerToUpdate);
        }
    }
}

rentoCarEliteSystem/rentoCarEliteSystem/Controllers/EmployeeController.cs
using EntityLayer;
using Microsoft.AspNetCore.Mvc;

namespace rentoCarEliteSystem.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login() { 
            return View(); 
        }

        [HttpPost]
        public EntityLayer.systemEntities.ResponseEL createEmployee([FromBody] EntityLayer.EmployeeEL employeeToCreate)
        {
            BussinesLayer.EmployeeBL myEmployee = new BussinesLayer.EmployeeBL();
            return myEmployee.createEmployee(employeeToCreate);

        }


        [HttpPost]
        public EmployeeEL login([FromBody] EmployeeEL employee)
        {
            BussinesLayer.EmployeeBL myEmployee = new BussinesLayer.EmployeeBL();
            return myEmployee.login(employee);
        }

        [HttpGet]
        public List<EmployeeEL> getAllEmployees() {
            BussinesLayer.EmployeeBL myEmployee = new BussinesLayer.EmployeeBL();
            return myEmployee.getAllEmployees();
        }

        [HttpPut]
        public EntityLayer.systemEntities.ResponseEL updateEmployee([FromBody] EmployeeEL employeeToUpdate)
        {
            BussinesLayer.EmployeeBL myEmployee = new BussinesLayer.EmployeeBL();
            return myEmployee.updateEmployee(employeeToUpdate);
        }


        [HttpDelete]
        public EntityLayer.systemEntities.ResponseEL deleteEmployee( int id)
        {
            BussinesLayer.EmployeeBL myEmployee = new BussinesLayer.EmployeeBL();
            return myEmployee.deleteEmployee(id);
        }

        
    }
}

rentoCarEliteSystem/rentoCarEliteSystem/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using rentoCarEliteSystem.Models;

namespace rentoCarEliteSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int code)
        {
            if (code == 404)
            {
                return View("Error404");
            }
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult newSell()
        {
            return View();
        }

        public IActionResult Dashboard()
        {
            return View();
        }


        
    }
}

rentoCarEliteSystem/rentoCarEliteSystem/Controllers/InsuranceController.cs
using Microsoft.AspNetCore.Mvc;

namespace rentoCarEliteSystem.Controllers
{
    public class InsuranceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public EntityLayer.systemEntities.ResponseEL createInsurance([FromBody] EntityLayer.InsuranceEL insuranceToCreate)
        {
            BussinesLayer.InsuranceBL myInsurance = new BussinesLayer.InsuranceBL();
            return myInsurance.createInsurance(insuranceToCreate);
        }
    }
}

rentoCarEliteSystem/rentoCarEliteSystem/Controllers/PaymentController.cs
using BussinesLayer;
using EntityLayer;
using Microsoft.AspNetCore.Mvc;

namespace rentoCarEliteSystem.Controllers
{
    public class PaymentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public EntityLayer.systemEntities.ResponseEL createPayment([FromBody ]PaymentEL paymentToCreate)
        {
            PaymentBL myPayment = new PaymentBL();
            return myPayment.createPayment(paymentToCreate);
        }
    }
}

rentoCarEliteSystem/rentoCarEliteSystem/Controllers/VehicleController.cs
using EntityLayer;
using Microsoft.AspNetCore.Mvc;

namespace rentoCarEliteSystem.Controllers
{
    public class VehicleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public EntityLayer.systemEntities.ResponseEL createVehicle([FromBody] VehicleEL vehicle)
        {
            BussinesLayer.VehicleBL vehicleBL = new BussinesLayer.VehicleBL();
            return vehicleBL.createVehicle(vehicle);
        }




        
        public List<VehicleEL> getAllVehicles()
        {
            BussinesLayer.VehicleBL vehicleBL = new BussinesLayer.VehicleBL();
            return vehicleBL.getAllVehicles();
        }

        [HttpPut]
        public EntityLayer.systemEntities.ResponseEL updateVehicle([FromBody] VehicleEL myVehicle)
        {
            BussinesLayer.VehicleBL vehicleBL = new BussinesLayer.VehicleBL();
            return vehicleBL.updateVehicle(myVehicle);
        }


        [HttpDelete]
        public EntityLayer.systemEntities.ResponseEL deleteVehicle(int vehicleId)
        {
            BussinesLayer.VehicleBL vehicleBL = new BussinesLayer.VehicleBL();
            return vehicleBL.deleteVehicle(vehicleId);
        }
    }
}

rentoCarEliteSystem/rentoCarEliteSystem/Views/Customer/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1 class="text-md-center">Informacion de Clientes</h1>



<div class="card p-3 mb-3 bg-light">
    <div class="d-flex align-items-center gap-2 justify-content-between">
        <div class="input-group w-50 d-none"
            <span class="input-group-text"><i class="fas fa-search"></i></span>
            <input type="text" id="searchInput" class="form-control" placeholder="Buscar...">
        </div>
        <button class="btn btn-success" id="downloadCsv">
            <i class="fas fa-file-csv"></i> Descargar .CSV
        </button>
        <button type="button" class="btn btn-primary" id="addNewCustomerButton">
            <i class="fas fa-user-plus"></i> Nuevo Usuario 
        </button>
    </div>
</div>


<!--Table rendering element-->

<div id="tableContainer"></div>

<!--Creation user Modal-->

<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel"><i class="fas fa-user-edit"></i> Formulario</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="userForm">
                    <div class="mb-3">
                        <label for="firstName" class="form-label"><i class="fas fa-id-badge"></i> First Name</label>
                        <input type="text" class="form-control" id="firstName" name="firstName" required>
                    </div>
                    <div class="mb-3">
                        <label for="lastName" class="form-label"><i class="fas fa-id-card"></i> Last Name</label>
                        <input type="text" class="form-control" id="lastName" name="lastName" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone" class="form-label"><i class="fas fa-phone"></i> Phone</label>
                        <input type="tel" class="form-control" id="phone" name="phone" required>
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label"><i class="fas fa-envelope"></i> Email</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="closeFormModalButton">
                    <i class="fas fa-times-circle"></i> Cerrar
                </button>
                <button id="addCustomerButton" type="button" class="btn btn-primary" >
                    <i class="fas fa-save"></i> Guardar
                </button>
                <button id="saveCustomerButton" class="btn btn-success" form="userForm" >
                    <i class="fas fa-edit"></i> Editar
                </button>
            </div>
        </div>
    </div>
</div>



<!--Confirm Deletion Modal-->


<div class="modal fade" id="deleteUserModal" tabindex="-1" aria-labelledby="deleteUserModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteUserModalLabel">
                    <i class="fas fa-exclamation-triangle text-warning"></i> Confirmar eliminación
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body" id="confirmationDeletrUserLabel">
                <p><i class="fas fa-question-circle text-danger"></i> ¿Estás seguro que deseas eliminar a este usuario?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    <i class="fas fa-ban"></i> Cancelar
                </button>
                <button id="deletCustomerButton" type="button" class="btn btn-danger">
                    <i class="fas fa-trash-alt"></i> OK
                </button>
            </div>
        </div>
    </div>
</div>

<script src="~/js/common.js"></script>
<script src="~/js/customer.service.js"></script>
<script src="~/js/customer.js"></script>

rentoCarEliteSystem/rentoCarEliteSystem/Views/Employee/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1 id="titlePannel" class="text-md-center">Empleados</h1>


<p id="infoPannel" class="text-md-center"></p>




<div class="card p-3 mb-3 bg-light">
    <div class="d-flex align-items-center gap-2 justify-content-between">
        <div class="input-group w-50 d-none"
            <span class="input-group-text"><i class="fas fa-search"></i></span>
            <input type="text" id="searchInput" class="form-control" placeholder="Buscar...">
        </div>
        <button class="btn btn-success" id="downloadCsv">
            <i class="fas fa-file-csv"></i> Descargar .CSV
        </button>
        <button type="button" class="btn btn-primary" id="addNewCustomerEmployee">
            <i class="fas fa-user-plus"></i> Nuevo Empleado
        </button>
    </div>
</div>


<!--Table rendering element-->

<div id="tableContainer"></div>

<!--Creation user Modal-->

<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel"><i class="fas fa-user-edit"></i> Formulario</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="userForm">
                    <div class="mb-3">
                        <label for="firstName" class="form-label"><i class="fas fa-id-badge"></i> Nombre</label>
                        <input type="text" class="form-control" id="firstName" name="firstName" required placeholder="Ingrese su nombre">
                    </div>
                    <div class="mb-3">
                        <label for="lastName" class="form-label"><i class="fas fa-id-card"></i> Apellido</label>
                        <input type="text" class="form-control" id="lastName" name="lastName" required placeholder="Ingrese su apellido">
                    </div>
                    <div class="mb-3">
                        <label for="phone" class="form-label"><i class="fas fa-phone"></i> Teléfono</label>
                        <input type="tel" class="form-control" id="phone" name="phone" required placeholder="Ingrese su número de teléfono">
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label"><i class="fas fa-envelope"></i> Email</label>
                        <input type="email" class="form-control" id="email" name="email" required placeholder="Ingrese su correo electrónico">
                    </div>
                    <div class="mb-3">
                        <label for="jobTitle" class="form-label"><i class="fas fa-briefcase"></i> Puesto</label>
                        <input type="text" class="form-control" id="jobTitle" name="jobTitle" required placeholder="Ingrese su puesto de trabajo">
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label"><i class="fas fa-lock"></i> Contraseña</label>
                        <input type="password" class="form-control" id="password" name="password" required minlength="6" placeholder="Ingrese su contraseña">
                    </div>
                    <div class="mb-3">
                        <label for="confirmPassword" class="form-label"><i class="fas fa-lock"></i> Confirmar Contraseña</label>
                        <input type="password" class="form-control" id="confirmPassword" name="confirmPassword" required minlength="6" placeholder="Confirme su contraseña">
                        <div id="passwordHelp" class="form-text text-danger"></div>
                    </div>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="closeFormModalButton">
                    <i class="fas fa-times-circle"></i> Cerrar
                </button>
                <button id="addEmployeeButton" type="button" class="btn btn-primary">
                    <i class="fas fa-save"></i> Guardar
                </button>
                <button id="saveEmployeeButton" class="btn btn-success" form="userForm">
                    <i class="fas fa-edit"></i> Editar
                </button>
            </div>
        </div>
    </div>
</div>



<!--Confirm Deletion Modal-->


<div class="modal fade" id="deleteUserModal" tabindex="-1" aria-labelledby="deleteUserModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteUserModalLabel">
                    <i class="fas fa-exclamation-triangle text-warning"></i> Confirmar eliminación
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body" id="confirmationDeletrUserLabel">
                <p><i class="fas fa-question-circle text-danger"></i> ¿Estás seguro que deseas eliminar a este usuario?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    <i class="fas fa-ban"></i> Cancelar
                </button>
                <button id="deletCustomerButton" type="button" class="btn btn-danger">
                    <i class="fas fa-trash-alt"></i> OK
                </button>
            </div>
        </div>
    </div>
</div>

<script src="~/js/common.js"></script>
<script src="~/js/employee.service.js"></script>
<script src="~/js/employee.pannel.js"></script>

rentoCarEliteSystem/rentoCarEliteSystem/Views/Employee/Login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = null;

}


    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-image: url(@Url.Content("~/img/loginWallpaper.jpg"));
            background-size: cover;
        }

        .login-container {
            background: rgba(255, 255, 255, 0.644);
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            text-align: center;
            width: 300px;
        }

        h2 {
            color: #1a1414;
        }

        label {
            color: #1f1010;
            display: block;
            text-align: left;
            margin-top: 10px;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            border: none;
            border-radius: 5px;
        }

        .login-btn {
            width: 100%;
            padding: 10px;
            background-color: #ff9800;
            color: #fff;
            border: none;
            border-radius: 5px;
            margin-top: 10px;
            cursor: pointer;
        }

        .social-login {
            display: flex;
            justify-content: space-between;
            margin-top: 15px;
        }

        .google-btn, .facebook-btn {
            width: 48%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }


    </style>

    <div class="login-container">
        <h2>Inicia Sesión</h2>
        <div class="w-100  d-flex align-items-center ">
            <i class="fa-solid fa-user-tie"></i>
        </div>
        <form id="formLogin" action="#" method="POST">
            <label for="username">Usuario</label>
            <input type="text" id="username" name="username" placeholder="Correo o Teléfono" required>

            <label for="password">Contraseña</label>
            <input type="password" id="password" name="password" placeholder="Contraseña" required>

            <button id="loginButton" class="login-btn">Ingresar</button>
        </form>
    </div>

<script src="~/js/common.js"></script>
<script src="~/js/employee.service.js"></script>
<script src="~/js/employee.js"></script>

rentoCarEliteSystem/rentoCarEliteSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    main {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        color: #fff;
        text-align: center;
        overflow: hidden;
        display: flex;
        flex-direction: column;
        min-height: 100vh;
    }

    .background {
        position: fixed;
        width: 100vw;
        height: 100vh;
        top: 0;
        left: 0;
        z-index: -1;
        background: linear-gradient(45deg, #ff416c, #ff4b2b, #1e90ff, #8a2be2);
        background-size: 400% 400%;
        animation: gradientBG 10s ease infinite;
    }

    @@keyframes gradientBG {
        0%

    {
        background-position: 0% 50%;
    }

    50% {
        background-position: 100% 50%;
    }

    100% {
        background-position: 0% 50%;
    }

    }

    .container {
        flex: 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    h1 {
        font-size: 2.5rem;
        margin-bottom: 10px;
    }

    p {
        font-size: 1.2rem;
        margin-bottom: 20px;
    }

    .btn {
        background-color: #e94560;
        color: #fff;
        padding: 10px 20px;
        text-decoration: none;
        font-size: 1.2rem;
        border-radius: 5px;
        transition: 0.3s;
    }

        .btn:hover {
            background-color: #f15a74;
        }
</style>

<main>
    <div class="background"></div>
    <div class="container">
        <h1 id="name">Bienvenido a Rent Elit Car System</h1>
        <p>Accede al panel interno para gestionar los vehículos y clientes.</p>
        <a asp-controller="Home" asp-action="newSell" class="btn">Ingresar al Sistema</a>
    </div>
</main>

<script src="~/js/home.js"></script>

rentoCarEliteSystem/rentoCarEliteSystem/Views/Shared/Error404.cshtml
@{
    ViewData["Title"] = "Página No Encontrada";
}

<div class="text-center">
    <h1 class="display-4 text-danger">404</h1>
    <!--404 image-->
    <img src="~/img/404image.png" alt="404" class="img-fluid" width="300"/>
    <h2 class="text-warning">Oops! Página no encontrada</h2>
    <p>Lo sentimos, la página que buscas no existe.</p>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Volver al inicio</a>
</div>

rentoCarEliteSystem/rentoCarEliteSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es" data-bs-theme="light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rent Car Elite System</title>

    <link rel="icon" href="~/img/logo.jpg" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bs-stepper/dist/css/bs-stepper.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tom-select/dist/css/tom-select.css">
    <script src="https://cdn.jsdelivr.net/npm/tom-select/dist/js/tom-select.complete.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/main.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/6.1.15/index.global.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">

</head>
<body>
    
    <header>
        <nav id="mainNavbar" class="navbar navbar-expand-lg navbar-light bg-white border-bottom shadow-sm p-3">
            <div class="container-fluid">
                <button class="btn btn-primary me-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebar">
                    <i class="fas fa-bars"></i> Menú
                </button>
                <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-globe"></i> Rent a Car Elite System
                </a>
            </div>
        </nav>
    </header>
        <!-- Sidebar -->
    <div class="offcanvas offcanvas-start" tabindex="-1" id="sidebar">
        <div class="offcanvas-header bg-primary text-white">
            <h5 class="offcanvas-title"><i class="fas fa-bars"></i> Menú</h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"></button>
        </div>
        <div class="offcanvas-body bg-light text-dark d-flex flex-column" id="sidebarBody">
            <ul class="nav flex-column flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">
                        <i class="fas fa-home"></i> Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="newSell">
                        <i class="fas fa-shopping-cart"></i> Nueva Venta
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="dashboard">
                        <i class="fas fa-chart-line"></i> Ventas
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Vehicle" asp-action="Index">
                        <i class="fas fa-car"></i> Vehicles
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customer" asp-action="Index">
                        <i class="fas fa-users"></i> Clientes
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Employee" asp-action="Index">
                        <i class="fas fa-user-tie"></i> Empleados
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" id="toggleTheme">
                        <i class="fas fa-moon"></i> Modo Oscuro
                    </a>
                </li>
            </ul>
            <ul class="nav flex-column mt-auto">
                <li class="nav-item">
                    <a class="nav-link text-danger" href="#" id="logoutButton">
                        <i class="fas fa-sign-out-alt"></i> Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <style>
        [data-bs-theme="dark"] .offcanvas,
        [data-bs-theme="dark"] .navbar {
            background-color: #212529 !important; /* Fondo oscuro */
            color: #ffffff !important; /* Texto blanco */
        }

            [data-bs-theme="dark"] .offcanvas .nav-link {
                color: #1d1616 !important;
            }

        [data-bs-theme="dark"] .offcanvas-header {
            background-color: #343a40 !important; /* Un poco más claro para diferenciar */
        }
    </style>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Rent a Car Elite System
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const themeToggleButton = document.getElementById("toggleTheme");
            const htmlElement = document.documentElement;

            const savedTheme = localStorage.getItem("theme") || "light";
            htmlElement.setAttribute("data-bs-theme", savedTheme);
            updateButtonIcon(savedTheme);

            themeToggleButton.addEventListener("click", function () {
                const currentTheme = htmlElement.getAttribute("data-bs-theme");
                const newTheme = currentTheme === "light" ? "dark" : "light";
                htmlElement.setAttribute("data-bs-theme", newTheme);
                localStorage.setItem("theme", newTheme);
                updateButtonIcon(newTheme);
            });

            function updateButtonIcon(theme) {
                if (theme === "dark") {
                    themeToggleButton.innerHTML = '<i class="fas fa-sun"></i> Modo Claro';
                } else {
                    themeToggleButton.innerHTML = '<i class="fas fa-moon"></i> Modo Oscuro';
                }
            }
        });
    </script>





</body>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.jsdelivr.net/npm/bs-stepper/dist/js/bs-stepper.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="~/js/global.js"></script>



</html>